In [1]:
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score

import lightgbm as lgb
import xgboost as xgb
import optuna

/Users/andyzhu/PycharmProjects/Kaggle_Titanic/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
train = pd.read_csv("train.csv", index_col="PassengerId")
test = pd.read_csv("test.csv", index_col="PassengerId")

In [26]:
train.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'Fare', 'Embarked', 'Deck', 'Title',
       'FamilySize', 'IsAlone', 'FamilyCategory', 'Log_Fare', 'IsChild',
       'TicketFrequency'],
      dtype='str')

In [4]:
train.isnull().sum().sort_values(ascending=False).head(10)

Survived      0
Pclass        0
Sex           0
Age           0
Fare          0
Embarked      0
Deck          0
Title         0
FamilySize    0
IsAlone       0
dtype: int64

In [5]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 1 to 891
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Survived         891 non-null    int64
 1   Pclass           891 non-null    int64
 2   Sex              891 non-null    str
 3   Age              891 non-null    int64
 4   Fare             891 non-null    float64
 5   Embarked         891 non-null    str
 6   Deck             891 non-null    str
 7   Title            891 non-null    str
 8   FamilySize       891 non-null    int64
 9   IsAlone          891 non-null    int64
 10  FamilyCategory   891 non-null    str
 11  Log_Fare         891 non-null    float64
 12  IsChild          891 non-null    int64
 13  TicketFrequency  891 non-null    int64
dtypes: float64(2), int64(7), str(5)
memory usage: 97.6 KB

In [6]:
#Baseline Logistic Regression

In [7]:
X_logistic = train.drop(columns=["Survived", "Fare", "FamilySize"])
X_logistic_test = test.drop(columns=["Fare", "FamilySize"])
y = train["Survived"]

In [8]:
X_logistic.columns

Index(['Pclass', 'Sex', 'Age', 'Embarked', 'Deck', 'Title', 'IsAlone',
       'FamilyCategory', 'Log_Fare', 'IsChild', 'TicketFrequency'],
      dtype='str')

In [18]:
X_logistic_test[X_logistic_test.Log_Fare.isnull()]

,Pclass,Sex,Age,Embarked,Deck,Title,IsAlone,FamilyCategory,Log_Fare,IsChild,TicketFreqCategory
PassengerId,,,,,,,,,,,
1044,3,male,60,S,0,Mr,1,Alone,NaN,0,Large

In [10]:
#Denn die TicketFrequency ist U Förmig mit Survived Korreliert
def ticket_freq_category(freq):
    if freq == 1:
        return 'Solo'
    elif freq <= 4:
        return 'Small'
    else:
        return 'Large'

X_logistic['TicketFreqCategory'] = X_logistic['TicketFrequency'].apply(ticket_freq_category)
X_logistic = X_logistic.drop(columns=['TicketFrequency'])

X_logistic_test['TicketFreqCategory'] = X_logistic_test['TicketFrequency'].apply(ticket_freq_category)
X_logistic_test = X_logistic_test.drop(columns=['TicketFrequency'])

In [11]:
numeric_cols_logistic = X_logistic.select_dtypes(include="number").columns
categorical_cols_logistic = X_logistic.select_dtypes(include="str").columns
categorical_cols_logistic

Index(['Sex', 'Embarked', 'Deck', 'Title', 'FamilyCategory',
       'TicketFreqCategory'],
      dtype='str')

In [12]:
numeric_preprocessor = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
])
categorical_preprocessor = Pipeline([
    ("onehot", OneHotEncoder(handle_unknown="ignore")),
])

preprocessor = ColumnTransformer([
    ("numeric_preprocessor", numeric_preprocessor, numeric_cols_logistic),
    ("categorical_preprocessor", categorical_preprocessor, categorical_cols_logistic),
])
Baseline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression())
])
Baseline.fit(X_logistic, y)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('numeric_preprocessor',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['Pclass', 'Age', 'IsAlone', 'Log_Fare', 'IsChild'], dtype='str')),
                                                 ('categorical_preprocessor',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['Sex', 'Embarked', 'Deck', 'Title', 'FamilyCategory',
       'TicketFreqCategory'],
      dtype='str'))])),
                ('classifier', LogisticRegression())])

In [29]:
Fold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [30]:
cross_val_score(Baseline, X_logistic, y, cv=Fold, scoring="accuracy").mean()

np.float64(0.8293766869625259)

In [15]:
def submission(model, X_test):
    y_pred = model.predict(X_test)

    Predictions = pd.DataFrame({
        "PassengerId": X_test.index,
        "Survived": y_pred,
    })
    return Predictions

In [16]:
submission_baseline = submission(Baseline, X_logistic_test)
submission_baseline.to_csv("submission_baseline.csv", index=False)

In [17]:
#Mit Boosting

In [21]:
X_tree = train.drop(columns=["Survived", "Log_Fare"])
X_tree_test = test.drop(columns=["Log_Fare"])

In [25]:
X_tree.columns

Index(['Pclass', 'Sex', 'Age', 'Fare', 'Embarked', 'Deck', 'Title',
       'FamilySize', 'IsAlone', 'FamilyCategory', 'IsChild',
       'TicketFrequency'],
      dtype='str')

In [24]:
categorical_cols_tree = X_tree.select_dtypes(include="str").columns
categorical_cols_tree

Index(['Sex', 'Embarked', 'Deck', 'Title', 'FamilyCategory'], dtype='str')

In [27]:
for col in categorical_cols_tree:
    X_tree[col] = X_tree[col].astype('category')
    X_tree_test[col] = X_tree_test[col].astype('category')

In [44]:
def objective(trial):
    params = {
        "objective": "binary",
        "metric": "binary_logloss",
        "verbosity": -1,
        "boosting_type": "gbdt",
        "n_estimators": trial.suggest_int("n_estimators", 50, 400),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.15, log=True),
        "num_leaves": trial.suggest_int("num_leaves", 4, 32),
        "max_depth": trial.suggest_int("max_depth", 2, 6),
        "min_child_samples": trial.suggest_int("min_child_samples", 5, 100),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 10.0, log=True),
    }

    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    scores = []

    for train_idx, val_idx in skf.split(X_tree, y):
        X_tr, X_val = X_tree.iloc[train_idx], X_tree.iloc[val_idx]
        y_tr, y_val = y.iloc[train_idx], y.iloc[val_idx]

        model = lgb.LGBMClassifier(**params, random_state=42)
        model.fit(
            X_tr, y_tr,
            eval_set=[(X_val, y_val)],
            callbacks=[lgb.early_stopping(50, verbose=False)],
        )

        preds = model.predict(X_val)
        scores.append(accuracy_score(y_val, preds))

    return np.mean(scores)

In [46]:
study = optuna.create_study(
    direction="maximize",
    study_name="titanic_lgbm_v2",
    storage='sqlite:///optuna_lgbm.db',
    load_if_exists=True,
)
study.optimize(objective, n_trials=50)

print("Best params:", study.best_params)
print("Best score:", study.best_value)

[I 2026-06-21 13:10:58,121] Using an existing study with name 'titanic_lgbm_v2' instead of creating a new one.
[I 2026-06-21 13:10:59,308] Trial 42 finished with value: 0.8473542150524136 and parameters: {'n_estimators': 366, 'learning_rate': 0.03566673249782356, 'num_leaves': 26, 'max_depth': 5, 'min_child_samples': 60, 'subsample': 0.9704869910119537, 'colsample_bytree': 0.9161135491339499, 'reg_alpha': 1.6410080215901946e-06, 'reg_lambda': 8.060630501790477e-07}. Best is trial 25 with value: 0.8518423200050217.
[I 2026-06-21 13:11:00,185] Trial 43 finished with value: 0.8406000878789781 and parameters: {'n_estimators': 285, 'learning_rate': 0.0321835440628769, 'num_leaves': 26, 'max_depth': 5, 'min_child_samples': 51, 'subsample': 0.9393666561571714, 'colsample_bytree': 0.9412147205917123, 'reg_alpha': 0.0005782377051011999, 'reg_lambda': 4.6958829734898475e-07}. Best is trial 25 with value: 0.8518423200050217.
[I 2026-06-21 13:11:01,301] Trial 44 finished with value: 0.8417425145941874 and parameters: {'n_estimators': 375, 'learning_rate': 0.02239461183373885, 'num_leaves': 23, 'max_depth': 5, 'min_child_samples': 59, 'subsample': 0.9666969572033453, 'colsample_bytree': 0.8306646370832187, 'reg_alpha': 1.7442266265826185e-06, 'reg_lambda': 4.7380551435532124e-08}. Best is trial 25 with value: 0.8518423200050217.
[I 2026-06-21 13:11:02,146] Trial 45 finished with value: 0.8305128366078716 and parameters: {'n_estimators': 334, 'learning_rate': 0.0515275571906246, 'num_leaves': 28, 'max_depth': 4, 'min_child_samples': 69, 'subsample': 0.9289876729216715, 'colsample_bytree': 0.8845366170501824, 'reg_alpha': 3.717642385086606e-08, 'reg_lambda': 6.962886821253344e-07}. Best is trial 25 with value: 0.8518423200050217.
[I 2026-06-21 13:11:03,087] Trial 46 finished with value: 0.8350009415604795 and parameters: {'n_estimators': 322, 'learning_rate': 0.03969795191321445, 'num_leaves': 25, 'max_depth': 5, 'min_child_samples': 66, 'subsample': 0.584472564602825, 'colsample_bytree': 0.8129460820912704, 'reg_alpha': 2.050361622115783e-08, 'reg_lambda': 1.715369142848539e-08}. Best is trial 25 with value: 0.8518423200050217.
[I 2026-06-21 13:11:04,497] Trial 47 finished with value: 0.8428598330299417 and parameters: {'n_estimators': 355, 'learning_rate': 0.027667887905310957, 'num_leaves': 29, 'max_depth': 6, 'min_child_samples': 35, 'subsample': 0.998681236918126, 'colsample_bytree': 0.7545950832550203, 'reg_alpha': 0.004693012781555293, 'reg_lambda': 1.402086527670303e-05}. Best is trial 25 with value: 0.8518423200050217.
[I 2026-06-21 13:11:05,398] Trial 48 finished with value: 0.8394953235829515 and parameters: {'n_estimators': 378, 'learning_rate': 0.02156497070704549, 'num_leaves': 14, 'max_depth': 3, 'min_child_samples': 18, 'subsample': 0.9777581759568603, 'colsample_bytree': 0.9856222173442056, 'reg_alpha': 4.506689791428196e-06, 'reg_lambda': 1.5057580542855438e-07}. Best is trial 25 with value: 0.8518423200050217.
[I 2026-06-21 13:11:06,093] Trial 49 finished with value: 0.8473416609126859 and parameters: {'n_estimators': 314, 'learning_rate': 0.13005322192107174, 'num_leaves': 12, 'max_depth': 6, 'min_child_samples': 53, 'subsample': 0.8669036969704893, 'colsample_bytree': 0.9044995089893952, 'reg_alpha': 1.0188499120035584e-08, 'reg_lambda': 0.004301592451578905}. Best is trial 25 with value: 0.8518423200050217.
[I 2026-06-21 13:11:07,368] Trial 50 finished with value: 0.8439834285355596 and parameters: {'n_estimators': 312, 'learning_rate': 0.03001716951371958, 'num_leaves': 22, 'max_depth': 6, 'min_child_samples': 53, 'subsample': 0.8644666207448223, 'colsample_bytree': 0.5039272993600681, 'reg_alpha': 2.1260187545395999e-07, 'reg_lambda': 0.004449077383287486}. Best is trial 25 with value: 0.8518423200050217.
[I 2026-06-21 13:11:08,294] Trial 51 finished with value: 0.8439708743958321 and parameters: {'n_estimators': 281, 'learning_rate': 0.0810958764057639, 'num_leaves': 11, 'max_depth': 6, 'min_child_samples': 46, 'subsample': 0.8365424125613707, 'colsample_bytree': 0.7138681695119272, 'reg_alpha': 0.25110758431392016, 'reg_lambda': 0.00016206964231703892}. Best is trial 25 with value: 0.8518423200050217.
[I 2026-06-21 13:11:08,911] Trial 52 finished with value: 0.8540895110162575 and parameters: {'n_estimators': 330, 'learning_rate': 0.12765404839393585, 'num_leaves': 12, 'max_depth': 6, 'min_child_samples': 64, 'subsample': 0.9102318778617753, 'colsample_bytree': 0.9014137360044202, 'reg_alpha': 1.0222248734906468e-08, 'reg_lambda': 0.0012156594146630277}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:09,537] Trial 53 finished with value: 0.8428535559600778 and parameters: {'n_estimators': 323, 'learning_rate': 0.1296532631376324, 'num_leaves': 14, 'max_depth': 6, 'min_child_samples': 64, 'subsample': 0.9087227363101864, 'colsample_bytree': 0.8955792933355211, 'reg_alpha': 1.0237587030607e-08, 'reg_lambda': 0.0004943898085904118}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:10,216] Trial 54 finished with value: 0.8473353838428223 and parameters: {'n_estimators': 349, 'learning_rate': 0.10013796763875277, 'num_leaves': 27, 'max_depth': 6, 'min_child_samples': 57, 'subsample': 0.795576367643884, 'colsample_bytree': 0.9161910178464827, 'reg_alpha': 2.6955250842396632e-08, 'reg_lambda': 1.967882487493857e-06}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:11,100] Trial 55 finished with value: 0.8406189190885694 and parameters: {'n_estimators': 330, 'learning_rate': 0.06796578722688248, 'num_leaves': 9, 'max_depth': 6, 'min_child_samples': 70, 'subsample': 0.8980603029464075, 'colsample_bytree': 0.9504375882397356, 'reg_alpha': 1.1343824599617671e-07, 'reg_lambda': 0.0019347564248882786}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:11,890] Trial 56 finished with value: 0.843977151465696 and parameters: {'n_estimators': 290, 'learning_rate': 0.09124200117881992, 'num_leaves': 11, 'max_depth': 6, 'min_child_samples': 52, 'subsample': 0.8699673568049706, 'colsample_bytree': 0.9304526468690432, 'reg_alpha': 9.723969552186663e-08, 'reg_lambda': 0.007340367840591781}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:12,783] Trial 57 finished with value: 0.8406000878789781 and parameters: {'n_estimators': 301, 'learning_rate': 0.042082423536798315, 'num_leaves': 15, 'max_depth': 6, 'min_child_samples': 49, 'subsample': 0.9196229143534663, 'colsample_bytree': 0.9765073395359473, 'reg_alpha': 2.210088555153077e-08, 'reg_lambda': 0.033727350659633705}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:13,533] Trial 58 finished with value: 0.8496014060636494 and parameters: {'n_estimators': 368, 'learning_rate': 0.1334066053586273, 'num_leaves': 25, 'max_depth': 6, 'min_child_samples': 63, 'subsample': 0.9489680000678672, 'colsample_bytree': 0.9052751900311417, 'reg_alpha': 1.4836947638818008, 'reg_lambda': 0.00010715727767902637}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:14,240] Trial 59 finished with value: 0.8372481325717155 and parameters: {'n_estimators': 372, 'learning_rate': 0.10574947303396914, 'num_leaves': 25, 'max_depth': 5, 'min_child_samples': 74, 'subsample': 0.9383147877257382, 'colsample_bytree': 0.8755370462901009, 'reg_alpha': 0.9614625599045018, 'reg_lambda': 8.689571478356303e-05}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:15,532] Trial 60 finished with value: 0.8484778105580315 and parameters: {'n_estimators': 388, 'learning_rate': 0.03353626234623226, 'num_leaves': 26, 'max_depth': 6, 'min_child_samples': 59, 'subsample': 0.9523866122046416, 'colsample_bytree': 0.9557023557219235, 'reg_alpha': 0.01155599309266098, 'reg_lambda': 1.5775135488470883e-05}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:16,333] Trial 61 finished with value: 0.8529659155106396 and parameters: {'n_estimators': 386, 'learning_rate': 0.13410170310655906, 'num_leaves': 23, 'max_depth': 6, 'min_child_samples': 64, 'subsample': 0.9469378727565116, 'colsample_bytree': 0.9992685394473327, 'reg_alpha': 1.5378528654794927, 'reg_lambda': 1.6740072170447057e-05}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:17,011] Trial 62 finished with value: 0.8518360429351578 and parameters: {'n_estimators': 387, 'learning_rate': 0.13237422001587662, 'num_leaves': 24, 'max_depth': 6, 'min_child_samples': 64, 'subsample': 0.9459806787044661, 'colsample_bytree': 0.9970760108881784, 'reg_alpha': 1.702246603661498, 'reg_lambda': 0.00014116112458514797}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:17,674] Trial 63 finished with value: 0.8484840876278952 and parameters: {'n_estimators': 383, 'learning_rate': 0.1319714706680438, 'num_leaves': 23, 'max_depth': 6, 'min_child_samples': 64, 'subsample': 0.8917835168090694, 'colsample_bytree': 0.9951556098089739, 'reg_alpha': 1.4759802582359844, 'reg_lambda': 3.813214277788778e-05}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:18,338] Trial 64 finished with value: 0.8406063649488418 and parameters: {'n_estimators': 358, 'learning_rate': 0.12127630338686313, 'num_leaves': 21, 'max_depth': 6, 'min_child_samples': 71, 'subsample': 0.9153432036825392, 'colsample_bytree': 0.9989283862030712, 'reg_alpha': 1.7251683404782587, 'reg_lambda': 0.00015415392111952836}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:18,950] Trial 65 finished with value: 0.8417362375243236 and parameters: {'n_estimators': 335, 'learning_rate': 0.13812583685818863, 'num_leaves': 24, 'max_depth': 6, 'min_child_samples': 76, 'subsample': 0.9363236028529783, 'colsample_bytree': 0.9725985984653835, 'reg_alpha': 0.3307244654652549, 'reg_lambda': 0.0007815793750575695}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:19,783] Trial 66 finished with value: 0.8417362375243238 and parameters: {'n_estimators': 343, 'learning_rate': 0.10708010529247683, 'num_leaves': 19, 'max_depth': 6, 'min_child_samples': 67, 'subsample': 0.9447381494974665, 'colsample_bytree': 0.9419237757089264, 'reg_alpha': 0.7402467379377409, 'reg_lambda': 3.9156124482698505e-05}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:20,036] Trial 67 finished with value: 0.8282719226664993 and parameters: {'n_estimators': 396, 'learning_rate': 0.11771972474896303, 'num_leaves': 23, 'max_depth': 6, 'min_child_samples': 84, 'subsample': 0.9075658676107997, 'colsample_bytree': 0.9597347451605778, 'reg_alpha': 7.928697927859235, 'reg_lambda': 0.0003718901764935413}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:20,934] Trial 68 finished with value: 0.8338961772644529 and parameters: {'n_estimators': 354, 'learning_rate': 0.08480236709132108, 'num_leaves': 28, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.9884804619434074, 'colsample_bytree': 0.9759772782117848, 'reg_alpha': 0.12035210218029624, 'reg_lambda': 9.181800625046595e-06}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:21,457] Trial 69 finished with value: 0.8350072186303432 and parameters: {'n_estimators': 387, 'learning_rate': 0.07041871683347918, 'num_leaves': 31, 'max_depth': 6, 'min_child_samples': 62, 'subsample': 0.9596119989333739, 'colsample_bytree': 0.9367700753932195, 'reg_alpha': 4.127271268527831, 'reg_lambda': 0.0014104350836568486}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:22,149] Trial 70 finished with value: 0.8484652564183041 and parameters: {'n_estimators': 367, 'learning_rate': 0.14842647324785976, 'num_leaves': 21, 'max_depth': 6, 'min_child_samples': 55, 'subsample': 0.926237244758008, 'colsample_bytree': 0.8537308393853894, 'reg_alpha': 0.06170868343500255, 'reg_lambda': 0.00014725184376895197}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:22,558] Trial 71 finished with value: 0.838390559286925 and parameters: {'n_estimators': 272, 'learning_rate': 0.09855314248822795, 'num_leaves': 27, 'max_depth': 2, 'min_child_samples': 68, 'subsample': 0.8849705605663789, 'colsample_bytree': 0.9842180496148012, 'reg_alpha': 2.306246328911925, 'reg_lambda': 0.0005346378242824033}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:22,905] Trial 72 finished with value: 0.8249011361496453 and parameters: {'n_estimators': 382, 'learning_rate': 0.13045706324887504, 'num_leaves': 23, 'max_depth': 6, 'min_child_samples': 62, 'subsample': 0.8943389689487413, 'colsample_bytree': 0.9936956597769052, 'reg_alpha': 7.113575087691978, 'reg_lambda': 3.967217610453268e-05}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:23,668] Trial 73 finished with value: 0.8462306195467957 and parameters: {'n_estimators': 398, 'learning_rate': 0.13621072402724266, 'num_leaves': 24, 'max_depth': 6, 'min_child_samples': 65, 'subsample': 0.8517077948603009, 'colsample_bytree': 0.9550129619239198, 'reg_alpha': 0.7100640620102964, 'reg_lambda': 2.646264022610977e-05}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:24,338] Trial 74 finished with value: 0.8428598330299415 and parameters: {'n_estimators': 341, 'learning_rate': 0.12063568674703222, 'num_leaves': 25, 'max_depth': 6, 'min_child_samples': 64, 'subsample': 0.8874813674543433, 'colsample_bytree': 0.9985880965213163, 'reg_alpha': 2.0914903429379006, 'reg_lambda': 6.503258669984514e-05}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:25,069] Trial 75 finished with value: 0.8394827694432239 and parameters: {'n_estimators': 364, 'learning_rate': 0.13770467141789586, 'num_leaves': 21, 'max_depth': 6, 'min_child_samples': 71, 'subsample': 0.9811510322587285, 'colsample_bytree': 0.9222329475513719, 'reg_alpha': 0.4042574210388234, 'reg_lambda': 2.6777600551101004e-06}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:25,786] Trial 76 finished with value: 0.8507187244994038 and parameters: {'n_estimators': 383, 'learning_rate': 0.10726257837749871, 'num_leaves': 23, 'max_depth': 6, 'min_child_samples': 58, 'subsample': 0.9050309780696649, 'colsample_bytree': 0.8877836272139723, 'reg_alpha': 0.023134993344011947, 'reg_lambda': 0.00031957790231284996}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:26,467] Trial 77 finished with value: 0.851861151214613 and parameters: {'n_estimators': 318, 'learning_rate': 0.10859194637787697, 'num_leaves': 19, 'max_depth': 5, 'min_child_samples': 59, 'subsample': 0.9486425918823996, 'colsample_bytree': 0.8878568204340247, 'reg_alpha': 0.014367005428517862, 'reg_lambda': 0.0002686988374534699}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:27,118] Trial 78 finished with value: 0.8417425145941875 and parameters: {'n_estimators': 297, 'learning_rate': 0.11092328483779088, 'num_leaves': 18, 'max_depth': 5, 'min_child_samples': 57, 'subsample': 0.9224083613029217, 'colsample_bytree': 0.8902318129076742, 'reg_alpha': 0.003064561680685268, 'reg_lambda': 0.0024547234127232083}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:27,855] Trial 79 finished with value: 0.8495762977841943 and parameters: {'n_estimators': 372, 'learning_rate': 0.10351028657608308, 'num_leaves': 19, 'max_depth': 6, 'min_child_samples': 58, 'subsample': 0.829577451044168, 'colsample_bytree': 0.8651227691625265, 'reg_alpha': 0.029109844203531517, 'reg_lambda': 0.00012069235291558672}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:28,657] Trial 80 finished with value: 0.8383654510074697 and parameters: {'n_estimators': 351, 'learning_rate': 0.08474517252107705, 'num_leaves': 27, 'max_depth': 6, 'min_child_samples': 76, 'subsample': 0.9046709350691052, 'colsample_bytree': 0.9034477451151135, 'reg_alpha': 0.0022706705688252263, 'reg_lambda': 0.00022677563024780026}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:29,466] Trial 81 finished with value: 0.8462180654070679 and parameters: {'n_estimators': 400, 'learning_rate': 0.0941566387525077, 'num_leaves': 22, 'max_depth': 5, 'min_child_samples': 55, 'subsample': 0.9466746473953263, 'colsample_bytree': 0.8397861816389482, 'reg_alpha': 0.034017851656204245, 'reg_lambda': 0.008615937037233427}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:30,222] Trial 82 finished with value: 0.8462306195467957 and parameters: {'n_estimators': 372, 'learning_rate': 0.10808183095018405, 'num_leaves': 19, 'max_depth': 6, 'min_child_samples': 58, 'subsample': 0.8320104189621883, 'colsample_bytree': 0.872585074379, 'reg_alpha': 0.03326545289307958, 'reg_lambda': 0.00010257818451420981}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:30,928] Trial 83 finished with value: 0.8451070240411775 and parameters: {'n_estimators': 388, 'learning_rate': 0.10347550554281609, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 63, 'subsample': 0.7598822197630609, 'colsample_bytree': 0.8620296176826647, 'reg_alpha': 0.00865453506800298, 'reg_lambda': 0.00027328514133178976}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:31,666] Trial 84 finished with value: 0.8417362375243236 and parameters: {'n_estimators': 374, 'learning_rate': 0.12441659264267185, 'num_leaves': 16, 'max_depth': 6, 'min_child_samples': 68, 'subsample': 0.8738759101161475, 'colsample_bytree': 0.8886713695851305, 'reg_alpha': 0.11351520308081982, 'reg_lambda': 0.0005237245137256979}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:32,292] Trial 85 finished with value: 0.8529596384407758 and parameters: {'n_estimators': 362, 'learning_rate': 0.11374085732146665, 'num_leaves': 18, 'max_depth': 6, 'min_child_samples': 60, 'subsample': 0.928519971813694, 'colsample_bytree': 0.9111329680772563, 'reg_alpha': 0.0010189787236383674, 'reg_lambda': 5.655063366687574e-05}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:32,951] Trial 86 finished with value: 0.8428598330299417 and parameters: {'n_estimators': 320, 'learning_rate': 0.11545340473658575, 'num_leaves': 26, 'max_depth': 6, 'min_child_samples': 49, 'subsample': 0.9291700365022011, 'colsample_bytree': 0.9088429151240713, 'reg_alpha': 0.0012349707224937325, 'reg_lambda': 5.9284707356227395e-05}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:33,530] Trial 87 finished with value: 0.8484652564183038 and parameters: {'n_estimators': 337, 'learning_rate': 0.13932872140712452, 'num_leaves': 18, 'max_depth': 6, 'min_child_samples': 60, 'subsample': 0.9651510734876125, 'colsample_bytree': 0.8210927981384138, 'reg_alpha': 0.00010144074739691529, 'reg_lambda': 2.221506622481343e-05}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:34,299] Trial 88 finished with value: 0.846218065407068 and parameters: {'n_estimators': 307, 'learning_rate': 0.07631231406293529, 'num_leaves': 7, 'max_depth': 5, 'min_child_samples': 66, 'subsample': 0.9166110393623169, 'colsample_bytree': 0.9353383696099983, 'reg_alpha': 0.0005670239944440545, 'reg_lambda': 8.345498601994462e-06}. Best is trial 52 with value: 0.8540895110162575.
[I 2026-06-21 13:11:35,124] Trial 89 finished with value: 0.8406126420187057 and parameters: {'n_estimators': 358, 'learning_rate': 0.1146879492388034, 'num_leaves': 29, 'max_depth': 6, 'min_child_samples': 73, 'subsample': 0.9463149925093061, 'colsample_bytree': 0.9639005098503721, 'reg_alpha': 0.4349731860316412, 'reg_lambda': 0.0013598276262006158}. Best is trial 52 with value: 0.8540895110162575.

Best params: {'n_estimators': 330, 'learning_rate': 0.12765404839393585, 'num_leaves': 12, 'max_depth': 6, 'min_child_samples': 64, 'subsample': 0.9102318778617753, 'colsample_bytree': 0.9014137360044202, 'reg_alpha': 1.0222248734906468e-08, 'reg_lambda': 0.0012156594146630277}
Best score: 0.8540895110162575

In [47]:
study.trials_dataframe().sort_values('value', ascending=False).head(10)

,number,value,datetime_start,datetime_complete,duration,params_colsample_bytree,params_learning_rate,params_max_depth,params_min_child_samples,params_n_estimators,params_num_leaves,params_reg_alpha,params_reg_lambda,params_subsample,state
52,52,0.854090,2026-06-21 13:11:08.297306,2026-06-21 13:11:08.908837,0 days 00:00:00.611531,0.901414,0.127654,6,64,330,12,1.022225e-08,0.001216,0.910232,COMPLETE
61,61,0.852966,2026-06-21 13:11:15.534601,2026-06-21 13:11:16.331454,0 days 00:00:00.796853,0.999269,0.134102,6,64,386,23,1.537853e+00,0.000017,0.946938,COMPLETE
85,85,0.852960,2026-06-21 13:11:31.669061,2026-06-21 13:11:32.291011,0 days 00:00:00.621950,0.911133,0.113741,6,60,362,18,1.018979e-03,0.000057,0.928520,COMPLETE
77,77,0.851861,2026-06-21 13:11:25.789339,2026-06-21 13:11:26.465190,0 days 00:00:00.675851,0.887857,0.108592,5,59,318,19,1.436701e-02,0.000269,0.948643,COMPLETE
25,25,0.851842,2026-06-21 13:10:37.949550,2026-06-21 13:10:38.906526,0 days 00:00:00.956976,0.951577,0.065880,5,63,333,28,4.254873e-08,0.018020,0.891182,COMPLETE
62,62,0.851836,2026-06-21 13:11:16.335657,2026-06-21 13:11:17.009617,0 days 00:00:00.673960,0.997076,0.132374,6,64,387,24,1.702247e+00,0.000141,0.945981,COMPLETE
32,32,0.850719,2026-06-21 13:10:44.357287,2026-06-21 13:10:45.127294,0 days 00:00:00.770007,0.916229,0.118380,6,65,324,25,3.995454e-08,0.001353,0.903931,COMPLETE
76,76,0.850719,2026-06-21 13:11:25.071092,2026-06-21 13:11:25.784992,0 days 00:00:00.713900,0.887784,0.107263,6,58,383,23,2.313499e-02,0.000320,0.905031,COMPLETE
58,58,0.849601,2026-06-21 13:11:12.785669,2026-06-21 13:11:13.531711,0 days 00:00:00.746042,0.905275,0.133407,6,63,368,25,1.483695e+00,0.000107,0.948968,COMPLETE
79,79,0.849576,2026-06-21 13:11:27.120799,2026-06-21 13:11:27.853963,0 days 00:00:00.733164,0.865123,0.103510,6,58,372,19,2.910984e-02,0.000121,0.829577,COMPLETE

In [50]:
best_model_lgbm = lgb.LGBMClassifier(**study.best_params)
best_model_lgbm.fit(X_tree, y)

LGBMClassifier(colsample_bytree=0.9014137360044202,
               learning_rate=0.12765404839393585, max_depth=6,
               min_child_samples=64, n_estimators=330, num_leaves=12,
               reg_alpha=1.0222248734906468e-08,
               reg_lambda=0.0012156594146630277, subsample=0.9102318778617753)

In [49]:
cross_val_score(best_model_lgbm, X_tree, y, scoring="accuracy").mean()

np.float64(0.8383842822170611)

In [51]:
submission_lgbm = submission(best_model_lgbm, X_tree_test)
submission_lgbm.to_csv("submission_lgbm_2.csv", index=False)